"""changed workout logs model

Revision ID: 034b6754a33c
Revises: 91782d94b947
Create Date: 2026-08-24 16:59:41.185670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034b6754a33c'
down_revision: Union[str, Sequence[str], None] = '91782d94b947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_logs', sa.Column('notes', sa.String(length=300), nullable=True))
    op.alter_column('workout_logs', 'workout_template_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('workout_logs', 'day_number')
    op.drop_column('workout_logs', 'workout_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_logs', sa.Column('workout_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('workout_logs', sa.Column('day_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('workout_logs', 'workout_template_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('workout_logs', 'notes')
    # ### end Alembic commands ###
