"""init

Revision ID: 64989dd97182
Revises: 
Create Date: 2026-07-29 15:45:38.921181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64989dd97182'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('equipment', sa.String(length=75), nullable=False),
    sa.Column('is_variation', sa.String(length=75), nullable=False),
    sa.Column('utility_type', sa.String(length=75), nullable=False),
    sa.Column('mechanics_type', sa.String(length=75), nullable=False),
    sa.Column('force_type', sa.String(length=75), nullable=False),
    sa.Column('target_muscles', sa.Text(), nullable=False),
    sa.Column('main_muscle', sa.String(length=75), nullable=False),
    sa.Column('secondary_muscles', sa.String(length=75), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('synergist_muscles', sa.Text(), nullable=True),
    sa.Column('stabilizer_muscles', sa.Text(), nullable=True),
    sa.Column('antagonist_muscles', sa.String(length=75), nullable=True),
    sa.Column('dynamic_stabilizer_muscles', sa.String(length=75), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_username', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('biometrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('chest', sa.Float(), nullable=True),
    sa.Column('hips', sa.Float(), nullable=True),
    sa.Column('manual_body_fat', sa.Float(), nullable=True),
    sa.Column('calculated_body_fat', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=150), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.String(length=100), nullable=False),
    sa.Column('program_description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('workout_type', sa.String(length=50), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('workout_type', sa.String(length=50), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_log_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_log_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_log_id'], ['workout_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_template_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_template_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workout_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_log_exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=True),
    sa.Column('top_weight', sa.Float(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('max_reps', sa.Integer(), nullable=False),
    sa.Column('max_rpe', sa.Float(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('detailed_sets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_log_exercise_id'], ['workout_log_exercises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_log_exercise_id')
    )
    op.create_table('personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_history_id', sa.Integer(), nullable=True),
    sa.Column('pr_type', sa.String(length=50), nullable=True),
    sa.Column('top_weight', sa.Float(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=150), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_history_id'], ['exercise_history.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_records')
    op.drop_table('exercise_history')
    op.drop_table('workout_template_exercises')
    op.drop_table('workout_log_exercises')
    op.drop_table('workout_templates')
    op.drop_table('workout_logs')
    op.drop_table('program_templates')
    op.drop_table('biometrics')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('exercises')
    # ### end Alembic commands ###
