"""added relationship between workout templates and logs

Revision ID: 91782d94b947
Revises: b09f09a0b4a0
Create Date: 2026-08-24 16:25:27.099371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91782d94b947'
down_revision: Union[str, Sequence[str], None] = 'b09f09a0b4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_logs', sa.Column('workout_template_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workout_logs', 'workout_templates', ['workout_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_logs', type_='foreignkey')
    op.drop_column('workout_logs', 'workout_template_id')
    # ### end Alembic commands ###
