"""added cascading and relationships to workout templates

Revision ID: b00ce863cb3f
Revises: 64989dd97182
Create Date: 2026-08-13 19:22:33.610362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00ce863cb3f'
down_revision: Union[str, Sequence[str], None] = '64989dd97182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biometrics', sa.Column('neck', sa.Float(), nullable=True))
    op.alter_column('biometrics', 'height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('workout_log_exercises_workout_log_id_fkey'), 'workout_log_exercises', type_='foreignkey')
    op.create_foreign_key(None, 'workout_log_exercises', 'workout_logs', ['workout_log_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('workout_template_exercises_workout_template_id_fkey'), 'workout_template_exercises', type_='foreignkey')
    op.create_foreign_key(None, 'workout_template_exercises', 'workout_templates', ['workout_template_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_template_exercises', type_='foreignkey')
    op.create_foreign_key(op.f('workout_template_exercises_workout_template_id_fkey'), 'workout_template_exercises', 'workout_templates', ['workout_template_id'], ['id'])
    op.drop_constraint(None, 'workout_log_exercises', type_='foreignkey')
    op.create_foreign_key(op.f('workout_log_exercises_workout_log_id_fkey'), 'workout_log_exercises', 'workout_logs', ['workout_log_id'], ['id'])
    op.alter_column('biometrics', 'height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('biometrics', 'neck')
    # ### end Alembic commands ###
