""" added juicy relationships between models

Revision ID: b09f09a0b4a0
Revises: b00ce863cb3f
Create Date: 2026-08-18 12:54:21.629272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09f09a0b4a0'
down_revision: Union[str, Sequence[str], None] = 'b00ce863cb3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workout_templates_program_id_fkey'), 'workout_templates', type_='foreignkey')
    op.create_foreign_key(None, 'workout_templates', 'program_templates', ['program_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_templates', type_='foreignkey')
    op.create_foreign_key(op.f('workout_templates_program_id_fkey'), 'workout_templates', 'program_templates', ['program_id'], ['id'])
    # ### end Alembic commands ###
